### ISSUE TITLE
Compilation problem

### ISSUE THREAD

**Issue by loganmill** [wernerd/gstzrtp#4]
Can you help with a compilation problem in the file gstzrtpfilter.c? In src/gstzrtpfilter.c, line 819 we have this call:

        zrtp_setMultiStrParams(filter->zrtpCtx, (char*)mspArr->data, mspArr->len);

...but the function wants 4 arguments. Here is the definition of the function, zrtp/zrtp/ZrtpCWrapper.cpp, line 215:

    void zrtp_setMultiStrParams(ZrtpContext* zrtpContext, char* parameters, int32_t length, ZrtpContext* master) {

...and here is its declaration, zrtp/zrtp/libcrtpcpp/ZrtpCWrapper.h, line 878:

     * @param master
     *     Pointer to the opaque ZrtpContext structure of the master ZRTP stream.
     */
    void zrtp_setMultiStrParams(ZrtpContext* zrtpContext, char* parameters, int32_t length, ZrtpContext* master);

I did have a quick look around to see if I could fix it, but didn't find any reference to a "master ZrtpContext" in the file.  Can you help? Was able to get the code to compile and successfully run the zrtpRecv/zrtpSend demos by setting the var to NULL, and nothing exploded, but would like to do better.

For what its worth, in my environment:

 - ubuntu 14.04
 - gstzrtp from https://github.com/wernerd/gstzrtp.git
 - gstreamer built from latest git clone of anongit.freedesktop.org
 - patches to gstzrtp for  gstreamer 1.0 from this post: https://github.com/wernerd/gstzrtp/issues/3
 - CRYPTO_STANDALONE set to TRUE in top-level CMakeLists.txt

...I  had to make the following additional changes to compile successfully:

1. In src/CMakeLists.txt, had to add 5 additional file references:

if (CRYPTO_STANDALONE)
    set(crypto_src
     ...
        ${zrtpSrcs}/bnlib/ec/curve25519-donna.c
        ${zrtpSrcs}/zrtp/crypto/skein256.cpp
        ${zrtpSrcs}/zrtp/crypto/skeinMac256.cpp
        ${zrtpSrcs}/zrtp/crypto/skein384.cpp
        ${zrtpSrcs}/zrtp/crypto/skeinMac384.cpp)

2. In  zrtp/bnlib/lbnmem.c, had to add the following includes:

#include <stdlib.h>
#include <string.h>
#include <strings.h>
#include <memory.h>

...at the top of the file, as the corresponding existing includes weren't making it through the preprocessor logic.

3. Had to install ccrtp-dev (on ubuntu 14.04: apt-get install libccrtp-dev), and explicitly build the zrtp subproject thus:

      cd zrtp ;  mkdir build ; cd build ; cmake .. ; make

...which was a bit surprising, as I believe the code is wrapping the gstreamer rtp implementation independently of the GNU version.

Many thanks!

-grd

**Comment by loganmill** [comment]
After looking around a bit, I can see the source of the problem, but not the solution.
zrtpcpp is a separate project from gstzrtp, and has undergone a fair
amount of evolution since the last gstzrtp update (> 2 years ago),
including changes to the api that gstzrtp calls.  The gstzrtp build
process "git clones" the latest zrtpcpp, bringing incompatible changes
into the gstzrtp build. 

Perhaps the shell script that does the clone, gstzrtp.sh, could be modified to
clone an earlier, compatible commit of zrtpcpp?

-grd

**Comment by dzzinstant** [comment]
Hi loganmill,

probably it is [this change] (https://github.com/wernerd/ZRTPCPP/commit/88af8762aeb3aa9fc7a3ef0267c9f8b0928a12fc) that causes the incompatibility.
In this case it should be sufficient to revert to V4.3.1 using `git checkout`, similar to this [patch for getzrtp.sh] (http://svn.gna.org/viewcvs/pidgin-zrtp/trunk/patches/gstzrtp-old_version.diff?revision=10)

**Comment by loganmill** [comment]
Thanks dzzinstant, that's fixed the compilation issue for me!
